# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger: none
pr: none

variables:
  dockerRegistryServiceConnection: 'GetJarRegistryServiceConnection'
  imageRepository: 'getjar'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: '$(Build.BuildId)'

pool:
  vmImage: ubuntu-latest

steps:
  
  - task: DockerInstaller@0
    inputs:
      dockerVersion: '17.09.0-ce'

  # - task: Docker@2
  #   displayName: Build and publish image to Azure Container Registry
  #   inputs:
  #     command: buildAndPush
  #     containerRegistry: $(dockerRegistryServiceConnection)
  #     repository: $(imageRepository)
  #     dockerfile: $(dockerfilePath)
  #     tags: |
  #       $(tag)
  - task: Docker@2
    inputs:
      containerRegistry: 'GetJarRegistryServiceConnection'
      repository: 'testjar.azurecr.io'
      command: 'buildAndPush'
      Dockerfile: '**/Dockerfile'